#!/bin/sh
#
# Start 3A daemon(Rockchip Auto Image Quality) for each /dev/mediaX device
#

# The xml db function is not ready yet
# export CAMERA_ENGINE_RKISP_XML_DB=/etc/iqfiles-db

case "$1" in
  start)
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
