// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  /** json-server --watch src/assets/json/db.json --port 3000 */
  // serverUrl: 'http://localhost:3000',
  serverUrl: 'http://192.168.1.101:80/cgi-bin/entry.cgi',
  scenarioUrl: '/image/0/scenario',
  osdUrl: '/osd/overlays',
  privacyMaskUrl: '/osd/privacy-mask',
  pictureMaskUrl: '/osd/image/picture',
  picMaskUrl: '/osd/image',
  lanUrl: '/network/lan',
  wlanUrl: '/network/wlan',
  wifiEnableUrl: '/network/wifi',
  wifiOnUrl: '/network/wifi?power=on',
  wifiOffUrl: '/network/wifi?power=off',
  wifiListUrl: '/network/wifi-list',
  scanWifiUrl: '/network/wifi?scan=1',
  wifiDeleteUrl: '/network/wifi?service=',
  ftpUrl: '/network/ftp',
  ftpTestUrl: '/network/ftp-test',
  autoWifiUrl: '/network/auto-cnt-wifi',
  ntpTimUrl: '/network-ntp/time',
  ntpInfoUrl: '/network-ntp',
  timezoneUrl: '/network-ntp/zone',
  upgradeNumUrl: '/system/firmware-upgrade?upload-type=resumable',
  upgradeUrl: '/system/firmware-upgrade?id=',
  rebootUrl: '/system/reboot',
  factoryResetUrl: '/system/factory-reset',
  preFactoryResetUrl: '/system/pre-factory-reset',
  upgradeEndUrl: '/system/firmware-upgrade?start=',
  freeRoomUrl: '/system/remain-space',
  sysLogUrl: '/system/export-log',
  sysDbUrl: '/system/export-db',
  infoDbUrl: '/system/import-db',
  infoUrl: '/system/device-info',
  parameterUrl: '/system/para/',
  loginUrl: '/system/login',
  addLoginUrl: '/system/login/add',
  modifyLoginUrl: '/system/login/modify',
  deleteLoginUrl: '/system/login/delete',
  reboot4DbUrl: '/system/import-db?start=1',
  storagePathUrl: '/storage/current-path',
  planAdvancePara: '/storage/advance-para',
  planTimingUrl: '/storage/snap-plan/0',
  planEventUrl: '/storage/snap-plan/1',
  quotaUrl: '/storage/quota/',
  hddListUrl: '/storage/hdd-list',
  searchUrl: '/storage/search',
  reviewDeleteUrl: '/storage/delete',
  formatUrl: '/storage/format/',
  ttlRoiUrl: '/roi',
  regionCropUrl: '/video/2/region-clip',
  advancedEncUrl: '/video/0/advanced-enc',
  motionRegionUrl: '/event/motion-detection/0',
  motionLinkageUrl: '/event/triggers/',
  memberListUrl: '/event/face-list',
  memberFaceUrl: '/event/face',
  memberAvatarUrl: '/event/face-picture?path=',
  memberSearchUrl: '/event/face-list?search=condition',
  snapSearchUrl: '/event/snapshot-record',
  snapImgUrl: '/event/face-picture?copy-path=',
  memberSearchByNameUrl: '/event/face-list?search=name',
  controlConditionSearchUrl: '/event/control-record?search=condition',
  controlNameSearchUrl: '/event/control-record?search=name',
  controlUrl: '/event/control-record',
  faceParaUrl: '/event/face-config',
  takePhotoUrl: '/event/take-photo',
  intrusionRegionUrl: '/event/regional-invasion/0',
  scheduleUrl: '/event/schedules/',
  batchInputBufferUrl: '/event/face-waiting',
  startRecordUrl: '/event/start-record',
  stopRecordUrl: '/event/stop-record',
  overlaySnapUrl: '/event/smart/cover',
  recordStatusUrl: '/event/get-record-status',
  resetFaceUrl: '/event/reset-face',
  resetSnapUrl: '/event/reset-snap',
  resetControlUrl: '/event/reset-control',
  checkFaceFail: '/event/check-face',
  lastFaceUrl: '/event/last-face',
  gatePeripheralsUrl: '/peripherals/gate',
  fillLightpheralsUrl: '/peripherals/fill-light',


  // for db.json
  // scenarioUrl: '/scenario',
  // searchUrl: '/storage/search',
  // osdUrl: '/osd',
  // lanUrl: '/lan',
  // wlanUrl: '/wlan',
  // infoUrl: '/device-info',
  // privacyMaskUrl: '/privacy-mask',
  // pictureMaskUrl: '/privacy-mask',
  // picMaskUrl: '/PicForm',
  // wifiEnableUrl: '/wifi-enabled',
  // wifiListUrl: '/wifi-list',
  // scanWifiUrl: '/scan',
  // wifiOnUrl: '/wifi-on',
  // wifiOffUrl: '/wifi-off',
  // wifiDeleteUrl: '/network/wifi?service=',
  // upgradeNumUrl: '/system/firmware-upgrade?upload-type=resumable',
  // upgradeUrl: '/system/firmware-upgrade?id=',
  // quotaUrl: '/quota-',
  // hddListUrl: '/hdd-list',
  // formatUrl: '/format/',
  // ttlRoiUrl: '/roi',
  // regionCropUrl: '/region-crop',
  // motionRegionUrl: '/motion-detection',
  // motionLinkageUrl: '/motion-linkage/',
  // rebootUrl: '/system/reboot',
  // factoryResetUrl: '/system/factory-reset',
  // upgradeEndUrl: '/system/firmware-upgrade?start=',
  // freeRoomUrl: '/system/remain-space',
  // sysLogUrl: '/system/export-log',
  // sysDbUrl: '/system/export-db',
  // infoDbUrl: 'system/import-db',
  // ntpTimUrl: '/ntp-time',
  // ntpInfoUrl: '/network-ntp',
  // timezoneUrl: '/ntp-zone',
  // memberListUrl: '/member-list',
  // memberFaceUrl: '/event/face/',
  // memberAvatarUrl: '/event/face-picture?path=',
  // memberSearchUrl: '/event/face-list?search=condition',
  // snapSearchUrl: '/event/snapshot-record',
  // snapImgUrl: '/event/face-picture?copy-path=',
  // memberSearchByNameUrl: '/event/face-list?search=name',
  // controlConditionSearchUrl: '/event/control-record?search=condition',
  // controlNameSearchUrl: '/event/control-record?search=name',
  // faceParaUrl: '/event/face-config',
  // takePhotoUrl: '/event/take-photo',
  // intrusionRegionUrl: '/event/regional-invasion/0',
  // parameterUrl: '/default-para/',
  // scheduleUrl: '/event/schedules/',
  // userUrl: '/system/user',
  // loginUrl: '/system/login',
  // addLoginUrl: '/system/login/add',
  // modifyLoginUrl: '/system/login/modify',
  // deleteLoginUrl: '/system/login/delete',
  // storagePathUrl: '/storage/current-path',
  // advancedEncUrl: '/video/0/advanced-enc',
  // batchInputBufferUrl: '/event/face-waiting',
  // overlaySnapUrl: '/event/smart/cover',
  // recordStatusUrl: '/event/get-record-status',
  // planAdvancePara: '/storage/advance-para',
  // stopRecordUrl: '/event/stop-record',
  // startRecordUrl: '/event/start-record',
  // planTimingUrl: '/storage/snap-plan/0',
  // planEventUrl: '/storage/snap-plan/1',
  // reboot4DbUrl: '/system/import-db?start=1',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
