#!/bin/sh

case "$1" in
	start)
                ispserver &
                startup_app_ipc -d rkispp_scale2 -W 960 -H 540 -w 720 -h 1280 -I 0 &
                printf "startup_app_ipc start\n"
		;;
	stop)
                killall -9 startup_app_ipc
		printf "stop finished\n"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
exit 0
