#!/bin/sh

case "$1" in
  start)
		printf "start ispserver"
		export HDR_MODE=0
		ispserver -n &
	;;
  stop)
		killall ispserver
		printf "stop ispserver"
        ;;
  restart|reload)
                $0 stop
                $0 start
	;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
