DEVICEIO_SITE = $(TOPDIR)/../external/deviceio
DEVICEIO_SITE_METHOD = local
DEVICEIO_INSTALL_STAGING = YES

ifeq ($(call qstrip,$(BR2_PACKAGE_RKWIFIBT_VENDOR)), CYPRESS)
DEVICEIO_CONF_OPTS += -DBSA=TRUE -DCYPRESS=TRUE
DEVICEIO_DEPENDENCIES += cypress_bsa
else ifeq ($(call qstrip,$(BR2_PACKAGE_RKWIFIBT_VENDOR)), BROADCOM)
DEVICEIO_CONF_OPTS += -DBSA=TRUE -DBROADCOM=TRUE
DEVICEIO_DEPENDENCIES += broadcom_bsa
else
ifeq ($(call qstrip,$(BR2_PACKAGE_RKWIFIBT_VENDOR)), REALTEK)
DEVICEIO_CONF_OPTS += -DBLUEZ5_UTILS=TRUE
DEVICEIO_CONF_OPTS += -DBLUEZ=TRUE
DEVICEIO_CONF_OPTS += -DREALTEK=TRUE
DEVICEIO_DEPENDENCIES += readline bluez5_utils libglib2
endif
endif

ifeq ($(call qstrip,$(BR2_ARCH)), arm)
DEVICEIO_BUILD_TYPE = arm
else ifeq ($(call qstrip, $(BR2_ARCH)), aarch64)
DEVICEIO_BUILD_TYPE = arm64
endif

DEVICEIO_CONF_OPTS += -DCPU_ARCH=$(BR2_ARCH) -DBUILD_TYPE=$(DEVICEIO_BUILD_TYPE)

DEVICEIO_DEPENDENCIES += wpa_supplicant alsa-lib

DEVICEIO_CONF_OPTS += -DCMAKE_INSTALL_STAGING=$(STAGING_DIR)

$(eval $(cmake-package))
